# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mdasifahamed89@yahoo.com
author_name: mdasifahamed
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: algokit-python-workshop

